### ISSUE TITLE
Refactor document fetching

### ISSUE THREAD

**Issue by hmans** [hmans/indiepants#52]
**As is:** fetching is done from within a `Document` instance.

**To be:** Move the actual fetching outside of `Document`. Get a hash of data, then copy that into a new or existing `Document` instance.

**Tasks:**

- [x] Move code from `DocumentFetching` into `Fetch` and make it return hash data
- [x] Adapt `Document.from_url` to first invoke `Fetch`, then decide how to act on it (deduplication etc.)
- [x] Only invoke `Fetch` for remote hosts
- [x] Reimplement `Document#fetch` using Fetch
- [x] Don't just assign all attributes; route them through a safe method that checks keys etc. (ex `consume_json`)
- [x] Deal with 404 et al
- [x] Remove old deduplication code (`#find_original` et al)
- [x] Specs!
