### ISSUE TITLE
Make Pants::Binary use PostgreSQL Large Objects

### ISSUE THREAD

**Issue by hmans** [hmans/indiepants#62]
...as they may be faster than bytea.

http://www.postgresql.org/docs/9.4/static/largeobjects.html
https://gist.github.com/hmans/cf18d182c51fb9191df6

**Tasks:**

- [ ] Remove `payload` from `Pants::Binary`
- [ ] Add a new `oid` column
- [ ] Add a virtual attribute that will, on save, be saved into a LO, storing the OID in the model
- [ ] Adapt Dragonfly datastore code

**Comment by hmans** [comment]
ActiveRecord doesn't like `oid` columns. :(

**Comment by hmans** [comment]
Closing for the time being. If ActiveRecord ever starts supporting `oid` columns natively, we can reconsider.
